---
title: "strike_analysis_v2"
output: html_document
date: "2025-04-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(kableExtra)
library(scales)
library(here) #to find working directory

```

```{r}
#checking for necessary data files
stopifnot(file.exists(here("strike_list_clean.csv")))
stopifnot(file.exists(here("bls66.csv")))
```



```{r}
df<- read_csv(here("strike_list_clean.csv"))

df <- df %>%
  rename(
    DateStarted = DateStartedOrReported,
    ContractType=ConractType,
    OnStrike='Number of Employees on Strike',
    TotalEmployees='Total employees at location'
    )%>%
  mutate(
    DateStarted = as.Date(DateStarted, format = "%m/%d/%Y"), 
    DateSettled = as.Date(DateSettled, format = "%m/%d/%Y"), 
    OnStrike = as.numeric(OnStrike),
    TotalEmployees=as.numeric(TotalEmployees),
    #DaysLost=NA, 
    StrikeLength = as.numeric(DateSettled - DateStarted),
    WorkerDaysLostMin=OnStrike*StrikeLength,
    WorkerDaysLostMax=TotalEmployees*StrikeLength,
    ActionType = str_to_lower(ActionType)
    )
```


```{r}
# Count occurrences of each ActionType in whole dataset
action_summary <- df %>%
  count(ActionType, sort = TRUE)

# Display using kable
action_summary %>%
  knitr::kable(
    caption = "Frequency of Each Action Type",
    format = "html",
    col.names = c("Action Type", "Count")
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed"),
    full_width = FALSE,
    position = "center"
  )
```

```{r}
# Count occurrences of each ActionType that ended in 1966
df66 <- df %>%
  filter(DateSettled>"1966-01-01")

action_summary <- df66 %>%
  count(ActionType, sort = TRUE)

# Display using kable
action_summary %>%
  knitr::kable(
    caption = "Frequency of Each Action Type",
    format = "html",
    col.names = c("Action Type", "Count")
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed"),
    full_width = FALSE,
    position = "center"
  )
```


```{r}

dfStrike66 <- df %>%
  filter(ActionType %in% c("wildcat", "strike"))%>%
  filter(DateSettled>="1966-01-01") #select all strikes settled in 1966. DF does not include strikes settled later than 1966.


sum_on_strike <- sum(dfStrike66$OnStrike, na.rm = TRUE)
sum_days_lost_min <- sum(dfStrike66$WorkerDaysLostMin, na.rm = TRUE)
sum_days_lost_max<-sum(dfStrike66$WorkerDaysLostMax,na.rm=TRUE)



# Create summary table
summary_table <- tibble(
  Metric = c(
    "Total Workers On Strike",
    "Total Worker-Days Lost (Min)",
    "Total Worker-Days Lost (Max)"
  ),
  Value = c(
    sum_on_strike,
    sum_days_lost_min,
    sum_days_lost_max
  )
) %>%
  mutate(Value = comma(Value))  # <-- HERE: add commas AFTER

# Print with nice styling
summary_table %>%
  kable(caption = "MOCOM Strike Data, 1966", format = "html") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    position = "center"
  )

```

```{r}

dfBLS<-read_csv(here("bls66.csv"))

dfBLS %>%
  head(10) %>%
  mutate(across(where(is.numeric), comma)) %>%
  knitr::kable(
    caption = "Preview of BLS 1966 Data",
    format = "html"
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed"),
    full_width = FALSE,
    position = "center"
  )

```

```{r}

```

